kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: redis
  name: redis-network-delay
spec:
  schedule: '*/3 * * * *'
  startingDeadlineSeconds: 5
  concurrencyPolicy: 'Allow'
  historyLimit: 1
  type: 'NetworkChaos'
  networkChaos:
    selector:
      namespaces:
        - redis
      labelSelectors:
        'object': 'redis'
    mode: all
    action: delay
    duration: 3s
    delay:
      latency: '3000ms'
      correlation: '100'
      jitter: '0ms'

