apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-exporter-sentinel-v7
  namespace: redis
spec:
  serviceName: redis-exporter-sentinel-v7
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter-sentinel-v7
  template:
    metadata:
      annotations:
        telegraf.influxdata.com/interval: 1s
        telegraf.influxdata.com/inputs: |+
          [[inputs.cpu]]
            percpu = false
            totalcpu = true
            collect_cpu_time = true
            report_active = true

          [[inputs.disk]]
            ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

          [[inputs.diskio]]

          [[inputs.kernel]]

          [[inputs.mem]]

          [[inputs.processes]]

          [[inputs.system]]
            fielddrop = ["uptime_format"]

          [[inputs.net]]
            ignore_protocol_stats = true

          [[inputs.procstat]]
          ## pattern as argument for pgrep (ie, pgrep -f <pattern>)
            pattern = "exporter"
        telegraf.influxdata.com/class: opentsdb
        telegraf.influxdata.com/env-fieldref-NAMESPACE: metadata.namespace
        telegraf.influxdata.com/limits-cpu: '300m'
        telegraf.influxdata.com/limits-memory: '300Mi'
      labels:
        app: redis-exporter-sentinel-v7
        exporter_object: redis
        object_mode: sentinel
        object_version: v7
        pod_type: exporter
    spec:
      nodeSelector:
        node-role: worker
      shareProcessNamespace: true
      containers:
      - name: redis-exporter-sentinel-v7
        image: registry-svc:25000/library/redis-exporter:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        args:
          - --redis.addr=redis://redis-sentinel-v7.redis:26379
          - --connection-timeout=1s
          - --include-system-metrics=true
          - --redis-only-metrics=true
          - --ping-on-connect=true
        env:
        - name: REDIS_PASSWORD
          value: weops
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 300Mi
        ports:
        - containerPort: 9121

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-exporter-sentinel-v7
  name: redis-exporter-sentinel-v7
  namespace: redis
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
    prometheus.io/path: '/metrics'
spec:
  ports:
  - port: 9121
    protocol: TCP
    targetPort: 9121
  selector:
    app: redis-exporter-sentinel-v7
